-- 코드를 입력하세요
SELECT OS.YEAR
, OS.MONTH
, COUNT(OS.USER_ID) AS PUCHASED_USERS
, ROUND(COUNT(OS.USER_ID) / (SELECT COUNT(USER_ID) 
                             FROM USER_INFO 
                             WHERE 
                             EXTRACT (YEAR FROM JOINED) =2021), 1) AS PUCHASED_RATIO
FROM 
(SELECT DISTINCT EXTRACT (YEAR FROM SALES_DATE) AS YEAR
    , EXTRACT (MONTH FROM SALES_DATE) AS MONTH
    , USER_ID 
    FROM ONLINE_SALE 
    GROUP BY EXTRACT (YEAR FROM SALES_DATE)
    , EXTRACT (MONTH FROM SALES_DATE)
    , USER_ID
) OS
, USER_INFO UI
WHERE OS.USER_ID = UI.USER_ID AND
UI.JOINED >= TO_DATE('2021-01-01', 'YYYY-MM-DD') AND JOINED <= TO_DATE('2021-12-31', 'YYYY-MM-DD')
GROUP BY YEAR, MONTH
ORDER BY
YEAR, MONTH;