-- 코드를 입력하세요
SELECT 
B.T - 1 AS HOUR,
COUNT(A.H) AS COUNT
FROM 
(SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS H FROM
ANIMAL_OUTS) A,
(SELECT LEVEL AS T FROM DUAL CONNECT BY LEVEL < 25) B
WHERE 
A.H(+) = B.T - 1
GROUP BY B.T
ORDER BY HOUR;