-- 코드를 입력하세요
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) FROM (SELECT AUTHOR.AUTHOR_ID,
    AUTHOR.AUTHOR_NAME,
    BOOK.CATEGORY,
    BOOK.PRICE * BOOK_SUM.SSUM AS TOTAL_SALES
FROM BOOK, 
    AUTHOR, 
    (SELECT BOOK_ID, SUM(BOOK_SALES.SALES) AS SSUM FROM BOOK_SALES WHERE SALES_DATE BETWEEN TO_DATE('2022-01-01', 'YYYY-MM-DD') AND TO_DATE('2022-01-31', 'YYYY-MM-DD') GROUP BY BOOK_ID) BOOK_SUM
WHERE BOOK.BOOK_ID = BOOK_SUM.BOOK_ID AND BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID)
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;