-- 코드를 입력하세요
SELECT ANIMAL_ID
, NAME
, NVL2(B.O, 'O', 'X') AS 중성화
FROM ANIMAL_INS A
, (SELECT ANIMAL_ID AS O FROM ANIMAL_INS 
   WHERE SEX_UPON_INTAKE LIKE '%Spayed%' 
   OR SEX_UPON_INTAKE LIKE '%Neutered%') B
WHERE A.ANIMAL_ID = B.O(+)
ORDER BY ANIMAL_ID;